language: rust
rust:
  - stable

os:
  - linux
  - osx

before_script:
  - rustup component add clippy

script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo build

notifications:
  email:
    on_success: never
